language: go

go:
  - 1.4

install:
  - mkdir -p $HOME/gopath/src/github.com/cloudfoundry-incubator/garden
  - git clone https://github.com/cloudfoundry-incubator/garden --recursive $HOME/gopath/src/github.com/cloudfoundry-incubator/garden
  - pushd $HOME/gopath/src/github.com/cloudfoundry-incubator/garden
  - git checkout 56735f8e803495acbf302c10a279229aae35bdc0
  - go get -u -v -t ./...
  - popd
  - go get -t -u -f -v ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - curl -L https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz | tar zxf - -C /tmp
  - mv /tmp/etcd-v0.4.6-linux-amd64/etcd $HOME/gopath/bin
  - go get github.com/apcera/gnatsd

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r -p -race -failOnPending -randomizeAllSpecs
